### ISSUE TITLE
Allow for single vector return values as well as scalars.

### ISSUE THREAD

**Issue by typingduck** [prometheus/nagios_plugins#1]
It appears that to monitor the rate of 500s you need to do:
    scalar(rate(my_webservice_requests{status=500}[5m]))

correct my if I'm wrong but this:
  rate(my_webservice_requests{status=500}[5m])
is not much different in return value so I'm wondering why scalar is required.

It looks like 'scalar' or 'count_scalar' is going to be present for no reason throughout our monitoring configs.

**Comment by beorn7** [comment]
Alertmanager is getting ready for prime time. We won't be tuning the nagios plugin anymore.

**Comment by typingduck** [comment]
:yellow_heart:
