### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by acotorelea** [prometheus/nagios_plugins#11]
Hello, from what I understood, this is for sending metrics prometheus > nagios. Is it possible viceversa  (nagios > prometheus) ? Thank you !

**Comment by grobie** [comment]
The prometheus/blackbox_exporter can be used for many Nagios style checks.

**Comment by beorn7** [comment]
If you have more support questions, please ask them on the [prometheus-users mailinglist](https://groups.google.com/forum/#!forum/prometheus-users") rather than in a GitHub issue.
