### ISSUE TITLE
Printing issue

### ISSUE THREAD

**Issue by smariko** [prometheus/nagios_plugins#12]
Hello,

I met some cases when the returned result is 0 even I have different value in Prometheus when throwing th same request.

After some debug I found that this is due to printf used in the code:

++ local _RESULT
+++ echo '[' 1507622733.059, '"47.319665666206134"' ']'
+++ jq -r '.[1]'
++ _RESULT=47.319665666206134
++ [[ 47.319665666206134 =~ ^-?[0-9]+\.?[0-9]*$ ]]
++ printf %.0F 47.319665666206134
/usr/lib/nagios/plugins/custom_scripts/check_prometheus_metric_test.sh: line 171: printf: 47.319665666206134: nombre non valable
+ PROMETHEUS_RESULT=0
++ get_prometheus_vector_metric '[

Sorry this is in french but after adding the line below, it worked perfectly, 

export LC_NUMERIC=C

Maybe it can help to add this in the code.

Regards
Sidiki

**Comment by beorn7** [comment]
Yeah, if the locale is set to one where the decimal point is a comma, it will not be able to parse the number. To avoid other locale related problems, we should probably set LC_ALL=C to be done with. I'll prepare a PR.
