### ISSUE TITLE
Possibility to monitor more than 1 element

### ISSUE THREAD

**Issue by sampath4970** [prometheus/nagios_plugins#20]
The script is explicitly capturing only the first element/result of a query/metric.

Is this limitation something to do with the Script itself of NagiosXI cannot handle more than one metric per service check?

**Comment by beorn7** [comment]
I don't really know. My understanding so far is that a Nagios plugin can only give back one result when it is run for a check.

**Comment by brian-brazil** [comment]
Yes, a given Nagois check can only return one success/failure.

**Comment by beorn7** [comment]
I'll assume then there is nothing we can do here. @sampath4970 , please follow up if you think otherwise.
