### ISSUE TITLE
Ability to write perfdata

### ISSUE THREAD

**Issue by yaron-idan** [prometheus/nagios_plugins#21]
We usually use perfdata to write the results of our checks back into graphite. It gives us an extra layer of visualisation when trying to investigate the previous state of the check. 
WDYT about adding this ability to this plugin? I can open the PR myself if you feel this would be useful.

**Comment by SuperQ** [comment]
I don't see why not. However, if you already have data in Prometheus it seems a little redundant. :grin:

**Comment by yaron-idan** [comment]
We often find perfdata gives us a good way to investigate the check results themselves over time.
I agree it can be achieved strictly by using prometheus but it's not as comfy.
Another point is that perfdata can also track the query duration and other interesting stats, but I couldn't fit it into the current scope.
