### ISSUE TITLE
check_prometheus_metric.sh does not properly parse 

### ISSUE THREAD

**Issue by mxb78** [prometheus/nagios_plugins#24]
With a vector as ret value, shell script does not parse properly following(obfuscated sens. info):

curl -sgG --insecure --data-urlencode 'query=irate(status_METRIC_total{app="SOMEAPP"}[5m])' "https://PROM.HOST/api/v1/query" | jq -r '.data.result' | jq -r '.[0].value?'

ret:
[
  1562331237.331,
  "0"
]

**Comment by mxb78** [comment]
full " jq -r '.data.result' " mangled ret looks like this:

[
  {
    "metric": {
      "app": "SOMEAPP",
      "cluster": "CLUSTER",
      "environment": "prod",
      "instance": "IP:8080",
      "job": "SOMEAPP",
      "kubernetes_pod_name": "POD",
      "pod_template_hash": "3175234914",
      "site": "SITE"
    },
    "value": [
      1562331724.023,
      "0"
    ]
  }
]

**Comment by beorn7** [comment]
Have you used the ` -t vector` flag?

**Comment by mxb78** [comment]
Sure I used. Without success, thus I started to look inside this script to see what is going on.

**Comment by beorn7** [comment]
Could you share the exact command and the output (error message and such)?

**Comment by mxb78** [comment]
/check_prometheus_metric.sh -H 'https://SERVER' -q 'irate(status_METRIC_total{app="APP"}[5m])' -w '5' -c '10' -n 'Failed ping: THIS -> THAT' -m 'ge' -t 'vector' -C --insecure
UNKNOWN - unable to parse prometheus response
Failed ping: THIS -> THAT is

function get_prometheus_vector_value {

  local _RESULT

  # return the value of the first element of the vector
  _RESULT=$(echo $1 | jq -r '.[0].value?')
  printf '%s' "${_RESULT}"

}

If I change  jq -r '.[0].value?' to  jq -r '.[0].value[1]' - I get what I want.

**Comment by beorn7** [comment]
I cannot reproduce your problem. For me, it works.

Note that the script doesn't just call jq -r '.[0].value?'` In https://github.com/prometheus/nagios_plugins/blob/master/check_prometheus_metric.sh#L242 , it is sending the output to `jq -r '.[1]'`. It is, in fact, already doing what you are suggesting.

I can only assume that something goes wrong querying Prometheus from within the script compared to what you curl. Or some subtle typing in the command line for `check_prometheus_metric.sh`?

**Comment by mxb78** [comment]
I found the issue. it's local one. sorry for the noise. Thanks for responding!
