### ISSUE TITLE
Warning / Critical intervals versus purely one-way comparisons.

### ISSUE THREAD

**Issue by Skeen** [prometheus/nagios_plugins#25]
Currently this plugin takes the following arguments:
```
    -w INT           Warning level value (must be zero or positive)
    -c INT           Critical level value (must be zero or positive)
    -m METHOD        Comparison method, one of gt, ge, lt, le, eq, ne
                     (defaults to ge unless otherwise specified)
```
While the `check_mysql_query` monitoring plugin takes: https://www.monitoring-plugins.org/doc/man/check_mysql_query.html
```
 -w, --warning=RANGE
    Warning range (format: start:end). Alert if outside this range
 -c, --critical=RANGE
    Critical range
```
Here is a mapping between the two syntaxes:

| Current Syntax | MySQL Query Syntax | Comment |
|----------------|--------------------|---------------------------|
| -m gt -w 5     | -w :5              | `> 5` -> outside the interval `]-infinity, 5]`|
| -m ge -w 5     | -w :4              | `>= 5` -> outside the interval `]-infinity, 4]` |
| -m lt -w 5     | -w 5:              | `< 5` -> outside the interval `[5, infinity[` |
| -m le -w 5     | -w 6:              | `<= 5` -> outside the interval `[6, infinity[` |
| -m eq -w 5     | -w :4 + -w 6: | `== 5` -> outside the interval `]-infinity, 4] ^ [6, infinity[` |
| -m ne -w 5     | -w 5:5             | `!= 5` -> outside the interval `[5, 5]` |

So while the MySQL syntax has troubles with `equals`, it does allow queries alike these:

| MySQL Query Syntax | Comment                                                   |
|--------------------|-----------------------------------------------------------|
| -w 10:20 -c 10:30  | Warning if outside 10:20, Critical if outside 10:30       |
| -w 10: -c :50      | Warning if it falls too low, critical if it goes too high |

The first one can be used for having an acceptable value within some number of standard derivations. The second one could be utilized for cpu load, where a low cpu load might signify that the process has stopped, while a high cpu load might signify that a realtime process cannot keep up.

I believe it is possible to support both syntaxes, without breaking backwards compatability, simply by expanding the current syntax with range support.

Which leaves me with multiple questions:
1. Was the MySQL Query Syntax considered, and if so, why was it rejected?
2. Would a PR introducing this syntax be welcome?

**Comment by beorn7** [comment]
The MySQL syntax was not considered. The goal of this plugin is mostly to keep it as simple as possible and as such cover simple cases of Nagios integration. For anything more involved, I'd consider the Nagios → Prometheus setup as too brittle.

Having said that, I wouldn't be opposed to a more powerful, backwards compatible syntax. However, note that this is just a simple shell script, utilizing the `test` command. The `check_mysql_query` plugin is implemented in C. I can imagine that it will be very tedious to implement the same query syntax in Bash. What I would like to avoid is to make this simple shell script overly complicated and hard to maintain.

**Comment by Skeen** [comment]
Hi @beorn7,
Thanks for your answer.

The reason I'm asking this question at all, is that we have developed an equivalent project to this in-house, but one which utilizes the MySQL syntax. Our script is purely implemented in bash as well.

If we could somehow get the MySQL syntax merged, this would allow us to utilize this project, instead of our in-house equivalent, and thus shift our efforts to this project, and to giving back to the community.

As for complexity, to support the mysql syntax, we just split the provided warning and critical value into start and stop of the interval using `cut`:
```
CRITICAL_VALUE_LOW=$(echo ${CRITICAL_VALUE} | cut -f1 -d':')
CRITICAL_VALUE_HIGH=$(echo ${CRITICAL_VALUE} | cut -f2 -d':')
WARNING_VALUE_LOW=$(echo ${WARNING_VALUE} | cut -f1 -d':')
WARNING_VALUE_HIGH=$(echo ${WARNING_VALUE} | cut -f2 -d':')
```
Assuming the value does not contain any colon, low will contain the entire input and high will be empty. Empty variables are then assigned to minus/plus infinity for low/high respectively.

To do the actual comparison we've opted to use `python` rather than a list of ifs and elses:
```
if ! python -c "exit(0 if (${QUERY_VALUE} <= ${CRITICAL_VALUE_HIGH} and ${QUERY_VALUE} >= ${CRITICAL_VALUE_LOW}) else 1)"; then
    echo "CRITICAL: Query value is not in range (${CRITICAL_VALUE_LOW} <= ${QUERY_VALUE} <= ${CRITICAL_VALUE_HIGH})! |${PERF_DATA}"
    exit 2
elif ! python -c "exit(0 if (${QUERY_VALUE} <= ${WARNING_VALUE_HIGH} and ${QUERY_VALUE} >= ${WARNING_VALUE_LOW}) else 1)"; then
    echo "WARNING: Query value is not in range (${WARNING_VALUE_LOW} <= ${QUERY_VALUE} <= ${WARNING_VALUE_HIGH})! |${PERF_DATA}"
    exit 1
else
    echo "OK: Query value is ok. (${QUERY_VALUE}) |${PERF_DATA}"
    exit 0
fi
```
As you already have `jq` as a dependency we could utilize this instead of `python`. I'm thinking one could produce a json object containing the query value, start and end + a jq query which produces the return code (0-->3) from that json object.

**Comment by beorn7** [comment]
With a dependency on Python, wouldn't it make way more sense then to write the whole check script in Python?

If you can pull it off and implement the whole thing with just bash and jq, that might work.

In different news, rather than heavily refactoring or amending the script here in the repo, I'd prefer a 3rd party project to provide this integration. If your script works well, could you just open-source it yourself, and we put a deprecation note here with a pointer to your repo?

The reason why we have this (very lightweight) integration with Nagios in the main repo is really just historical. (SoundCloud needed it, and initially the Prometheus development was mostly at SoundCloud.) SoundCloud eventually got rid of Nagios completely, and I have never touched it ever since, so I'm actually a bad maintainer now. I can hardly judge any change here that is more involved.

**Comment by Skeen** [comment]
> With a dependency on Python, wouldn't it make way more sense then to write the whole check script in Python?

The dependency on Python in our version was not intended, and I would like to get rid of it while potentially merging our code with this.
 
> If you can pull it off and implement the whole thing with just bash and jq, that might work.

I will give it a shot.

> In different news, rather than heavily refactoring or amending the script here in the repo, I'd prefer a 3rd party project to provide this integration. If your script works well, could you just open-source it yourself, and we put a deprecation note here with a pointer to your repo?

My argument against this would be that some people might depend on this, and thus have their infrastructure broken as our script is not compatible with this one. I would rather merge the two projects, and help maintain this one.

**Comment by beorn7** [comment]
> My argument against this would be that some people might depend on this, and thus have their infrastructure broken as our script is not compatible with this one.

They don't have to migrate to your script. They could just keep using this one.

If they want new features, they are going to change something anyway.

Me being not the right person to maintain this repo is just a minor point. The more serious issue is really that this repo is by now essentially a misfit in the Prometheus GH org. I'm happy to maintain the status quo to not break anybody, but I'm very reluctant to add or change anything significant here.

**Comment by Skeen** [comment]
Hi @beorn7 

I finally got around to finishing up the merge between this and our in-house version, the result is to be found here: https://github.com/magenta-aps/check_prometheus_metric

I believe I have managed to maintain 100% backwards compatibility, although I might get disproved on that statement in the future.

If you want to, you can take a look, any feedback is welcome.

**Comment by beorn7** [comment]
That looks really cool. (Disclaimer: I cannot try it out in my setup as I don't use Nagios anywhere anymore, see above. And likewise I cannot really judge how good this would look to a real Nagios expert.)

Assuming your approach is sane, I'd love to mark the prometheus/nagios_plugins repo as deprecated and add a link to magenta-aps/check_prometheus_metric in the README.md here.
We could also add it to the list of integrations on https://prometheus.io (with the side effect that a PR there will trigger more people to look at magenta-aps/check_prometheus_metric and give it a better sanity check then I can).

**Comment by Skeen** [comment]
Hi,

That would be lovely, but I'd probably want to add some integration tests before we do so.

I'll try to give look into that tomorrow or so. I'll post back here when I have evidence towards the robustness of the Nagios integration, and then we can look into proceeding?

**Comment by beorn7** [comment]
Sounds perfect. Thank you very much.

**Comment by Skeen** [comment]
I added some basic integration tests against Icinga 2, which is what we use in-house.

It looks to be working just fine, but I'd love to get some review / sanity checking on it.

**Comment by beorn7** [comment]
I'll advertise this on the [developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

**Comment by beorn7** [comment]
See [post](https://groups.google.com/forum/#!topic/prometheus-developers/6QecbIgb5n4).

**Comment by beorn7** [comment]
Now that our plan is put into action, I'll close this.
